### ISSUE TITLE
URL in repository description and readme is wrong

### ISSUE THREAD

**Issue by towerofnix** [isitchristmas/isitchristmas.github.io#1]
Here:

![In the repository description](https://user-images.githubusercontent.com/9948030/32761867-b63e1f2e-c8ed-11e7-930d-70f0b84185e9.png)

..and here:

![In the README](https://user-images.githubusercontent.com/9948030/32761874-c6c3bb24-c8ed-11e7-9e85-5a43aaf73a3d.png)

These should link to https://isitchristmas.com.

**Comment by konklone** [comment]
Fixed, changed links to https://isitchristmas.github.io (and turned on HTTPS enforcement in repo settings for GitHub Pages).
